### ISSUE TITLE
Oitc Agent delivers no output after last Update

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1005]
After last 3 steps
- apt-get update
- apt-get dist-upgrade
- openitcockpit-update
all seems to be fine...but ALL installed agent are delivering nothing ....

![image](https://user-images.githubusercontent.com/44997840/84913299-ae209d00-b0ba-11ea-805d-8475ecafd382.png)

**Comment by binsky08** [comment]
Hallo @infofrs,

ist der Agent im Pull oder Push Modus?
Welches Kommando hat denn der OITC_AGENT_ACTIVE Service, der hier nicht funktioniert?
Sollte das Kommando mit '/opt/openitc/receiver/bin/poller.php' beginnen, dieses bitte mal manuell auf der Konsole mit dem zusätzlichen Parameter -v ausführen und den Output hier posten.

**Comment by infofrs** [comment]
Das wird schwierig da dort immer nur noch folgendes steht...
![image](https://user-images.githubusercontent.com/44997840/84922143-bcc08180-b0c5-11ea-8861-4348a53c79ee.png)

**Comment by binsky08** [comment]
Hallo @infofrs,

ist der Agent im **Pull oder Push Modus**?
Welches Kommando hat denn der **OITC_AGENT_ACTIVE** Service, der hier nicht funktioniert?
Sollte das Kommando mit '/opt/openitc/receiver/bin/poller.php' beginnen, dieses bitte mal manuell auf der Konsole mit dem zusätzlichen Parameter -v ausführen und den Output hier posten.

**Comment by infofrs** [comment]
Pull

/opt/openitc/frontend/bin/cake nagios_xml_notification -q --type Host --notificationtype $NOTIFICATIONTYPE$ --hostname "0d63ef63-9ce1-43a5-9a9c-db872b537175" --hoststate "$HOSTSTATE$" --hostaddress "192.168.10.123" --hostoutput "$HOSTOUTPUT$" --contactmail "$CONTACTEMAIL$" --contactalias "$CONTACTALIAS$" --hostackauthor "$NOTIFICATIONAUTHOR$" --hostackcomment "$NOTIFICATIONCOMMENT$" --format "both"

**Comment by nook24** [comment]
_English version below_

Vermutlich betrifft dieses Problem mehrere Leute, deshalb gleich auf deutsch und englisch…

Leider wurde dies von einem Fehler im aktuellen openITCOCKPIT 4 Beta Release versuchst. Dabei konnten es passieren, dass die Kommandos mit den IDs 30 und 31 überschrieben werden. Dies ist an deinem System leider passiert.

Du könntest einmal unter `/opt/openitc/nagios/backup/` schauen, ob du noch ein Backup von vor dem Update hast und die Kommandos manuell wiederherstellen.
Alternativ würde eine komplette Neuinstallation das Problem auch beheben.

Vielen Danke das du den Fehler gemeldet hast und die Beta Version ausprobierst!

---

Unfortunately, this issue was caused by the latest openITCOCKPIT 4 Beta release. During the upgrade process it was possible that the commands with the IDs 30 and 31 gets overwritten by the system. It seems that exactly this happen to your system.

To resolve the issue, you could check if you have an old backup (from before the latest update get installed) in `/opt/openitc/nagios/backup/`. Maybe you can use the information from the backup to restore your old commands.
Otherwise a fresh installation of openITCOCKPIT would also resolve the issue.

Many thanks for reporting this and testing the Beta version!

**Comment by infofrs** [comment]
Kein Problem. Ist ja in Beta und Homelab und nicht in der Produktionsumgebung. Schliesse den Issue daher.
