### ISSUE TITLE
Feature Request: iframe with username:password@ip-address

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1006]
Would like to integrate iframes in dashboards with other grafana dashboards....
"http://user:passwor@grafana-server-ip:3000/d/8-IIDKMik/fritz-box-smarthome?orgId=1&from=1592373472768&to=1592395072768&var-switch_name=All" as an example to implement other nice local runing dashboards....
![prometheus_fritzbox](https://user-images.githubusercontent.com/44997840/84917565-ca730880-b0bf-11ea-9201-7541df7960a6.JPG)

**Comment by nook24** [comment]
As an openITCOCKPIT veteran as you are I know you remember the iframe Widget from openITCOCKPIT 2.x...
![oitc_v2_browser](https://user-images.githubusercontent.com/9019992/94026867-811b0f00-fdba-11ea-8b4a-d748835b391f.png)

We removed the iframe widget years ago because most websites have restrictions and can't be loaded into an iframe anymore or it may cause any other problems with mixed content of http and https connections etc...

How ever, with the next release, the iframe widget is back - but disabled by default. To use the iframe widget you need to enable `ENABLE_IFRAME_IN_DASHBOARDS` in the systemsettings of openITCOCKPIT 4. This will enable a new Widget called `Website`.

It will show you an message that you will have mostlekly a bad experience with iframes:
![website_widget](https://user-images.githubusercontent.com/9019992/94027487-2c2bc880-fdbb-11ea-86b7-b4e0f3842a4f.png)
like so:
![bad_iframe](https://user-images.githubusercontent.com/9019992/94027493-3057e600-fdbb-11ea-831a-4bca7a0c207a.png)

How ever, for internal sites where you have full control and can control the `X-Frame-Options` it's hopefully helpful 🙂
![Bildschirmfoto 2020-09-23 um 16 40 28](https://user-images.githubusercontent.com/9019992/94027916-a78d7a00-fdbb-11ea-97c4-6e26554a807f.png)
