### ISSUE TITLE
agent services ignore check/retry interval

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1051]
i have some virtual server hosts which come to some resource usage peaks (disk load, memory usage, etc.) from time to time. to avoid unnecessary notifications within these short peaks i change the parameters of the check:
- check intervals: 5m
- retry intervals: 2m (or with some hosts even 5m)
- max check attempts: 7 (or even 9)

the max check attempts are recognized and used but the check interval and - even more important - retry interval are not. according to the history the intervals are 1m - regardless what i set in the options.

the agent checks are configured in push mode. even when the agent pushes new values every minute - for soft state/hard state count only the value sets every interval set should count

**Comment by nook24** [comment]
Hi @exa-mk if the openITCOCKPIT Agent is running in Push-Mode, the `Check interval` and `Retry interval` values will be ignored. This is due to the fact that the Agent will push all check results to the openITCOCKPIT Server.

You should check the `interval` value of your openITCOCKPIT Agent. This should be 60 by default, so the openITCOCKPIT Agent will push it's check results every minute: https://github.com/it-novum/openitcockpit-agent/blob/master/example_config.cnf#L145-L147

To suppress notifications on load peaks, you need to adjust the value of `Max. number of check attempts`. So a value of `Max. number of check attempts=10` with an interval of 60 should delay the first notification by 10 minutes.

**Comment by nook24** [comment]
Hi @exa-mk did this resolve the issue for you?
