### ISSUE TITLE
Agent loose connection to Server

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#1054]
after minutes some Agents can´t be connected 

UNKNOWN: cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by Terminator81** [comment]
or:
UNKNOWN: cURL error 7: Failed to connect to 130.50.103.12 port 3333: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by nook24** [comment]
Hi @Terminator81. Could you please provide more information about your client system and if your are using an HTTP proxy?

**Comment by Terminator81** [comment]
Hi @nook24 
Windows Server 2016
Sophos Intercept X Advanced for Server with EDR
proxy: autoconfig with Proxy-Script on the firewall

after restarte the agent service it works vor some hours.

**Comment by nook24** [comment]
I think this relates to #1057 
We are investigating this...

**Comment by Terminator81** [comment]
is there anything new on this topic?

**Comment by AndiMacTen** [comment]
Hello,
is this issue under investigation? We're barely able to monitor Windows Systems via agent.
Restart or reinstall of the agent helps temporary but doesn't last long.

**Comment by nook24** [comment]
Thank you very much for your patience. Unfortunately things are different on Windows which explains why most Agent related issues are on Windows operating systems. How ever we made great progress on this and looking forward for the next stable release of the Agent to finally resolve the issues.

**Pull Model** (#1054)
We found a memory leak in the Web Server implementation on Windows. Most likely this memory leak causes the Agent not to respond on HTTP requests after some hours (or days). 
In addition, we are investigating an issue in combination with proxy servers and the openITCOCKPIT Poller script.


**Push Mode** (#1057)
The TLS certificates generated by the system where stored with Windows line endings on Windows Operating Systems. This changed the hash sum of the TLS certificate which is used by openITCOCKPIT.

When a new TLS Certificate is generated the latest hash sum will be stored in memory. As soon as the Agent got restarted on a Windows OS, the hash sum gets regenerated from the certificate file stored on disk. Due to this file got written with windows new lines the hash sum was wrong and the openITCOCKPIT server declined the check results.
This got fixed with https://github.com/it-novum/openitcockpit-agent/commit/e124220321890650d3f190a52a6499e62a8505f3

We have built a new Nightly Version if you want to test it: https://openitcockpit.io/files/openitcockpit-agent-nightly/openitcockpit-agent-1.0.5.msi

**Comment by AndiMacTen** [comment]
Hello,
we're still facing connection issues with windows servers. Agent version is 1.0.6. Randomly the agent is not reachable anymore. `UNKNOWN: cURL error 7: Failed to connect to <IP> port 3333: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`
Removing the server out of the agent configuration (push mode), restarting the oitcAgentSvc service and reestablishing the agent connection solves the situation, but just temporary – for a few days, sometimes only for a few hours.

**Comment by nook24** [comment]
I'm working on a refurbished version of the Agent: https://github.com/it-novum/openitcockpit-agent/tree/2.0
I will reply to this issue as soon as the first nightly builds are available for testing (hopefully tomorrow).

**Comment by 7845258** [comment]
Hi, 

Bei uns auch ähnliches Verhalten:

Windows Server 2019 Standart (VM in einer VMware vSphere Umgebung)
Agent Version 1.0.6
Agent ist im Pull Modus (alles standartmässig konfiguriert)
OpenITCockpit Version 4.1.1


Fehlermeldung in OpenITCockpit um ca. um 23.15 Uhr: 
UNKNOWN: cURL error 7: Failed to connect to 172.17.0.227 port 3333: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Log des Agenten:

020-11-19 23:12:21,883; INFO; 457; Running default checks
2020-11-19 23:12:58,921; INFO; 1634; 172.17.0.186 - - [19/Nov/2020 23:12:58] "GET / HTTP/1.1" 200 -
2020-11-19 23:13:34,733; INFO; 457; Running default checks
2020-11-19 23:13:57,329; INFO; 1634; 172.17.0.186 - - [19/Nov/2020 23:13:57] "GET / HTTP/1.1" 200 -
2020-11-19 23:14:47,612; INFO; 457; Running default checks
2020-11-19 23:14:56,740; INFO; 1634; 172.17.0.186 - - [19/Nov/2020 23:14:56] "GET / HTTP/1.1" 200 -
2020-11-19 23:15:49,401; INFO; 457; Running default checks
2020-11-20 00:01:08,382; INFO; 457; Running default checks
2020-11-20 01:06:01,886; INFO; 457; Running default checks
2020-11-20 02:11:08,084; INFO; 457; Running default checks
2020-11-20 03:15:55,333; INFO; 457; Running default checks
2020-11-20 04:20:19,149; INFO; 457; Running default checks
2020-11-20 05:24:25,387; INFO; 457; Running default checks
2020-11-20 06:28:49,188; INFO; 457; Running default checks

Der Service auf dem Windows Server 2019 "oitcAgentSvc" hat nach dem Fehler immer noch den Status "Running"

Wenn wir den Service "oitcAgentSvc" neu starten geht es wieder...

Um 23.15 Uhr wird jeweils ein Snapshot per VeeamBackup & Replication der betreffenden VM gemacht
und genau da kommt es meistens zu dem Fehler...

**Comment by nook24** [comment]
We released the first public beta version of the openITCOCKPIT Monitoring Agent 2.0. 
To improve the stability we kindly ask you to join the testing phase. Especially if you facing connectivity issues at the moment.

All information and any issues can be found and reported here: https://github.com/it-novum/openitcockpit-agent/issues/43

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/

Version 3.0 should resolve your issue. Please report any issues with Version 3.x into this issue: https://github.com/it-novum/openitcockpit-agent-go/issues/47
