### ISSUE TITLE
Agent not submitting data after restart

### ISSUE THREAD

**Issue by Patriciawa** [it-novum/openITCOCKPIT#1057]
Hi,

I've noticed that after a while, the agent stops pushing data, it's in push mode. As far as I can tell, it happens when a (windows) machine restarts, can this be a config error? It happened to me on a Windows 10 machine and a small windows server that has been restarted, the services all say OK, but the last time it has pushed data is before the machines have been restarted. Once restarted I have to completely remove the host, services and push cache, then add it again and it works. When the machine starts, the agent is also active in services, restarting doesn't make a difference. Any idea what is going wrong?

![image](https://user-images.githubusercontent.com/49994443/92738533-51ace100-f37c-11ea-933c-35f47a1d4392.png)
Hasn't pushed data for plus 1 day.

Thanks,

Patrick

**Comment by m4ximum** [comment]
Hello @Patriciawa 
We will investigate this behaviour. I have opened an issue regarding this in our internal bugtracker

**Comment by Patriciawa** [comment]
@m4ximum Thanks for letting me know!

**Comment by Patriciawa** [comment]
Is there any workaround available? I find it weird that OITC says the service is OK when it hasn't pushed any data for 7+ days...

**Comment by nook24** [comment]
Unfortunately the freshness checks were not enabled for the Agent services by default 😞 This will be fixed with the next version but this patch will only effect new systems.

To enable the freshness check on your current installation you can run the folowing SQL statement:
```SQL
UPDATE `servicetemplates`
SET `freshness_checks_enabled`=1, `freshness_threshold`=300
WHERE `servicetemplatetype_id`=16
AND `active_checks_enabled`=0
AND `freshness_checks_enabled`=0
```
After that you need to run `Refresh monitoring configuration` via the openITCOCKPIT interface to apply the changes.
![Bildschirmfoto 2020-09-23 um 08 23 10](https://user-images.githubusercontent.com/9019992/93974402-0cbe7c80-fd76-11ea-87da-f1665bcd1ecf.png)


If an Agent is not submitting data for longer than 5 minutes, the state will change to `Unknown`:

![Bildschirmfoto 2020-09-23 um 08 10 12](https://user-images.githubusercontent.com/9019992/93974304-ec8ebd80-fd75-11ea-9b33-9bccefc25a90.png)

**Comment by nook24** [comment]
We are still investigating all reported issues with the openITCOCKPIT Agent on Windows.

**Comment by Patriciawa** [comment]
@nook24  Many thanks for your reply. Active checks works now! Please let me know when there is some kind of workaround available for the agent.

**Comment by exa-mk** [comment]
I ran into a similar behaviour as @Patriciawa .
Thanks for the freshness check hint @nook24 .

**Comment by nook24** [comment]
Thank you very much for your patience. Unfortunately things are different on Windows which explains why most Agent related issues are on Windows operating systems. How ever we made great progress on this and looking forward for the next stable release of the Agent to finally resolve the issues.

**Pull Model** (#1054)
We found a memory leak in the Web Server implementation on Windows. Most likely this memory leak causes the Agent not to respond on HTTP requests after some hours (or days). 
In addition, we are investigating an issue in combination with proxy servers and the openITCOCKPIT Poller script.


**Push Mode** (#1057)
The TLS certificates generated by the system where stored with Windows line endings on Windows Operating Systems. This changed the hash sum of the TLS certificate which is used by openITCOCKPIT.

When a new TLS Certificate is generated the latest hash sum will be stored in memory. As soon as the Agent got restarted on a Windows OS, the hash sum gets regenerated from the certificate file stored on disk. Due to this file got written with windows new lines the hash sum was wrong and the openITCOCKPIT server declined the check results.
This got fixed with https://github.com/it-novum/openitcockpit-agent/commit/e124220321890650d3f190a52a6499e62a8505f3

We have built a new Nightly Version if you want to test it: https://openitcockpit.io/files/openitcockpit-agent-nightly/openitcockpit-agent-1.0.5.msi

**Comment by exa-mk** [comment]
@nook24 : Thanks for the update and nightly build. Now the cert problem in push mode is fine.
However all in all it's kind of worse: The service stops sending data now on all windows hosts after running a while. After a restart it's fine again for some time.

**Comment by AndiMacTen** [comment]
Thank you very much for the updated agent.
unfortunately same behavior as @exa-mk is reporting. The agent still stops working after a while.

**Comment by exa-mk** [comment]
After about two days now I have to say the 1.0.4 version was way more stable (in point of data packages arriving at the openitc host) than the 1.0.5 one - at least in push mode. 
I switched back to use 1.0.4 again (with converting the certs to LF line endings manually before).

**Comment by nook24** [comment]
Also, did you reboot the System after the update of the openITCOCKPIT Agent?

**Comment by Patriciawa** [comment]
I had the same problem @exa-mk had. After switching to 1.0.6 all is stable, time will tell.

**Comment by exa-mk** [comment]
I agree, the 1.0.6 seems to be stable now.
However, on old Windows 2003 servers (which we still have 2 of) it doesn't send any data at all - only the 1.0.4 is working there.

@nook24 : IMHO a reboot isn't required if the service is (manually) stopped before. You should fix the installer to stop the service automatically before updating or uninstalling, then it should be fine ;)

**Comment by m4ximum** [comment]
@exa-mk 

A working Agent for operating systems which are End-of-life (and for windows server 2003 its over 5 years now) is not planned. 
But you can get in contact with Christoph.Wess@it-novum.com for professional support and development.
Also the sourcecode of the Agent is opensource https://github.com/it-novum/openitcockpit-agent and can be modified as needed if you want to do it by yourself.

**Comment by exa-mk** [comment]
@m4ximum : I know w2003 is way out of support and didn't expect for you to look into it. I just wondered why 1.0.4 is working and newer ones aren't and tough at least I should mention it.

Thanks a lot for the help so far.

**Comment by nook24** [comment]
> IMHO a reboot isn't required if the service is (manually) stopped before. You should fix the installer to stop the service automatically before updating or uninstalling, then it should be fine ;)

The service gets stopped by the msi installer. The reboot message is from Windows or so. I dont know it for sure. I know it is not specifically defined in the msi so 🤷‍♂️

> I know w2003 is way out of support and didn't expect for you to look into it. I just wondered why 1.0.4 is working and newer ones aren't and tough at least I should mention it.

This is due to the .NET version 4.5.
You could try to run the agent from source as @m4ximum suggested. To run it as service, you need to compile the service wrapper with an older .NET version: https://github.com/it-novum/openitcockpit-agent/tree/development/msi/OitcAgentSvc

Or use some other tools/methods to run the python agent as service.

**Comment by AndiMacTen** [comment]
I'd confirm 1.0.6 is much more stable. Works fine for some hosts.
Nevertheless we're seeing lots of `UNKNOWN: No data received from agent` messages at some hosts. We can't find anything those hosts have in common. Tried different update paths, adding completely new systems...

Check interval is 5m. We set the retry interval to 30s since the second check attempt is successful mostly, so a hard state DOWN can be avoided. 

We’re using pull mode exclusively. Oitc version is 4.1.0.
The only oitc agent check which works stable on all hosts is OITC_AGENT_ACTIVE.
Any ideas?

The log entries for the effected systems look like this:
Date | Type | Record
-- | -- | --
22.10.2020 15:06 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:06 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   15:06 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:06 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:06 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   15:06 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:05 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:05 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:05 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   15:05 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:05 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:05 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   15:05 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:04 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:04 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:04 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   15:04 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:04 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:04 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   15:04 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:03 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:03 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:03 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   15:03 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:03 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:03 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   15:03 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:02 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:02 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:02 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   15:02 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:02 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:02 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   15:02 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:01 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:01 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:01 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   15:01 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:01 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:01 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   15:01 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:00 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:00 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   15:00 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   15:00 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:00 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   15:00 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   15:00 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:59 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:59 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:59 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   14:59 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:59 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:59 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   14:59 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:58 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:58 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:58 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   14:58 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:58 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:58 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   14:58 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:57 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:57 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:57 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   14:57 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:57 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:57 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   14:57 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:56 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:56 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:56 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:56 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:55 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   14:55 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   14:55 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:55 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:54 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:54 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:54 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:54 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   14:54 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   14:54 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:54 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:53 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:53 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:53 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:53 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   14:53 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   14:53 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:53 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:52 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:52 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:52 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:52 | Service unknown | SERVICE   ALERT: Server-A;Check windows service running   Service-A;UNKNOWN;SOFT;2;UNKNOWN: No data received from agent
22.10.2020   14:52 | Service ok | SERVICE   ALERT: Server-A;Check windows service running Service-A;OK;SOFT;3;OK:   Amount: 1 services.
22.10.2020   14:52 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:52 | Service ok | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;OK;SOFT;2;OK: Amount: 1 processes. Memory usage: 0.05%.   CPU usage: 0%.
22.10.2020   14:51 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent
22.10.2020   14:51 | Service unknown | SERVICE   ALERT: Server-A;Check Process C:\Program   Files\[...]\[...].exe;UNKNOWN;SOFT;1;UNKNOWN: No data received from agent

**Comment by nook24** [comment]
Hi @AndiMacTen,

all checks processed by the openITCOCKPIT Agent are passive, except `OITC_AGENT_ACTIVE`.
The Service `OITC_AGENT_ACTIVE` only exists if the Agent is running in pull mode. It is the service which queries all the data from the Agent and process all other checks at the same time.

By default the `OITC_AGENT_ACTIVE` has an check and retry interval of 60 seconds. So all passive checks will get new results every 60 seconds (+ few seconds latency maybe)

The message `UNKNOWN: No data received from agent` gets triggered by the freshness check. So for me it looks like that your freshness threshold is set to low. I would recommend to set it to 5 minutes:
![Bildschirmfoto 2020-10-23 um 13 56 39](https://user-images.githubusercontent.com/9019992/97001035-fa339080-1537-11eb-9dc7-bb8e459ec98b.png)

PS: The state history is a better method to show the state change events than the log entries are:
![Bildschirmfoto 2020-10-23 um 14 02 30](https://user-images.githubusercontent.com/9019992/97001280-6a421680-1538-11eb-8d21-8c5bdd68ebf4.png)

**Comment by AndiMacTen** [comment]
Hi @nook24 
thank you for explanation. I guess I'll contact support. Have the feeling something is not working as it should. 
Intervals are configured as recommended. 
Knowing this is another behavior as in my previous post. A host I added yesterday has been monitored fine all day and night, until this morning 8AM. Since then 'UNKNOWN: No data received from agent'. Removing the agent config out of oITC, restarting agent service, new agent discovery procedure helped to get the host monitored again but this is not an legitim workaround if we plan to monitor 500 Windows hosts.

cheers
