### ISSUE TITLE
create auto-dependency for passive agent checks

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1075]
I activated the freshness checks for my agent push setup like explained in issue #1057. Now every time the agent fails or doesn't send any data (especially on windows hosts where the agent is still buggy) a big bunch of >100 services is spam alarming me (and my colleagues).

To stop this I created a service dependency on the agent service itself on some hosts. However, this is very painful to do manually on each host, especially when the services to be monitored are still changing regularly.

Is there a possibility to create this dependency somehow automatically?

**Comment by nook24** [comment]
The related issue #1057 is related t the old python agent, which is end of life. I guess since all are using the new Go based agent, this issue is not relevant anymore.


Please see my comment here https://github.com/it-novum/openITCOCKPIT/issues/1095#issuecomment-1434444654 for more information about how to reduce the amount of service notifications without the need of service dependencies.
