### ISSUE TITLE
Setup.sh not work

### ISSUE THREAD

**Issue by matfil92** [it-novum/openITCOCKPIT#1086]
Hi,
I've tried to install the new version of openitcockpit v4 into Debian 10, Ubuntu 18 or Ubuntu 20 but when I launch /opt/openitc/frontend/SETUP.sh I always have this error

Copy required system files
Create required system folders
chmod: cannot access '/opt/openitc/nagios/libexec/check_icmp': No such file or directory
chmod: cannot access '/opt/openitc/nagios/libexec/check_dhcp': No such file or directory
Enable new systemd services
Create local MySQL configuration and database
Unsupported distribution or /etc/mysql/debian.cnf is missing!

And the installation will be interrupted. 
I've tried to investigate and honestly this file not exist 
check_icmp and check_dhcp

Anyone have solved or have this problem?

**Comment by nook24** [comment]
Good morning @matfil92,

I noticed that openITCOCKPIT complains about MySQL in both of your issues:
`Unsupported distribution or /etc/mysql/debian.cnf is missing!`
And in #1087 `PHP Warning: file_get_contents(/opt/openitc/etc/mysql/mysql.cnf): failed to open stream: No such file or directory in`

Do you use MariaDB or some other MySQL installation which is not from the official repository of the distribution? Please also make sure that no MySQL server is installed before you install openITCOCKPIT. Otherwise you have to do all the MySQL setup manually (totally not recommended for new users 🙂)

check_icmp and check_dhcp are included in the package `openitcockpit-monitoring-plugins` which will be installed automatically.

I have also tested the installation on Ubuntu 20.04 right now, it works without any errors. So please make sure to start on a fresh installation of Ubuntu where no Apache, MySQL or anything else is already installed and [follow the instructions](https://openitcockpit.io/download_server/) step by step

**Comment by matfil92** [comment]
Hi @nook24 ,
thanks for your reply. Please see my recording screen on fresh install of Ubuntu 20.04 minimal. 

As you can see I've followed your procedure and when I try to launch the last command they fail as indicated previously.
[https://youtu.be/Auziq3iDeEs](url) 
Could you help me please?

**Comment by binsky08** [comment]
Nice video, but at 2:30 you have already added the Ubuntu Repository and continue to add the Debian Repository too.
**Thats not good :D**

It can't end well. Didn't finish watching the video.

**Comment by matfil92** [comment]
sorry @binsky08 now I've run the installer with this command and I have always the same problem.
Could you please highlight here what command I don't need to launch?


`
add-apt-repository universe
apt-get install apt-transport-https curl gnupg2 ca-certificates
curl https://packages.openitcockpit.io/repokey.txt | apt-key add -

echo "deb https://packages.openitcockpit.io/openitcockpit/$(lsb_release -sc)/stable $(lsb_release -sc) main" > /etc/apt/sources.list.d/openitcockpit.list
apt-get update
`
and
`
apt-get install openitcockpit
`

when I run this `/opt/openitc/frontend/SETUP.sh` I've the same problem

Please let me know what command is wrong because if I not run `echo "deb https://packages.openitcockpit.io/openitcockpit/$(lsb_release -sc)/stable $(lsb_release -sc) main" > /etc/apt/sources.list.d/openitcockpit.list` they doesn't find the openitcockpit package 

I'm waiting your kindly help
Thanks

**Comment by binsky08** [comment]
> Nice video, but at 2:30 you have already added the Ubuntu Repository and continue to add the Debian Repository too.
> **Thats not good :D**
> 
> It can't end well. Didn't finish watching the video.

sorry, forget it, doesn't matter, its a generic command

**Comment by nook24** [comment]
> Nice video, but at 2:30 you have already added the Ubuntu Repository and continue to add the Debian Repository too.

Ubuntu and Debian are using the same repository. Thats not the issue. But to highlight the Ubuntu and Debian specific parts on the website, I added a border around them.

However, as already guessed in my first post your system is **not** going to install a MySQL Server. Probably because it is already installed as part of the Hetzner Cloud Image.
Please check this by running:
```
sudo dpkg -l |grep mysql
```

You can see in your Video, that your system will not install a MySQL Server:
![Bildschirmfoto 2020-11-17 um 15 23 53](https://user-images.githubusercontent.com/9019992/99407753-c148ca80-28ef-11eb-816b-e566c7237546.png)

I just did the installation on an DigitalOcean VM where you can clearly see that the MySQL server will get installed:
![Bildschirmfoto 2020-11-17 um 16 00 20](https://user-images.githubusercontent.com/9019992/99407861-dc1b3f00-28ef-11eb-9cc1-f64e9bc0908c.png)

So what ever is already installed to this Cloud Image, remove it.
Otherwise you need to create the MySQL configuration for openITCOCKPIT by yourself **before** you run the `apt-get install` command. This is only for experienced users and not recommended for beginners. 
Especially because it is only documented in the source code:https://github.com/it-novum/openITCOCKPIT/blob/development/SETUP.sh#L76-L122

**Comment by matfil92** [comment]
Yes I confirm that this was the problem thanks for help me
