### ISSUE TITLE
servicedependencies of agent push services do not work

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1095]
I made the effort to configure a servicedependency on each host making the agent (push mode) checks dependent on the check of the agent itself.

Unfortunately if I don't add the 'ok' notification_failure_criteria (which makes no sense and imho is a stupid preset by the way) it doesn't seem to work. 
Example:
The agent on a host fails, the state of all agent checks go to UNKNOWN and still all checks are spamming notifications instead of just the check on the agent.
![grafik](https://user-images.githubusercontent.com/69202794/101874033-6588fe80-3b88-11eb-83a8-1d989258ee23.png)
![grafik](https://user-images.githubusercontent.com/69202794/101874235-ca445900-3b88-11eb-863f-68ecbb4a55c9.png)

**Comment by nook24** [comment]
For Agents running in **push mode**:
Instead of defining a service dependency, you should use the `openITCOCKPIT Agent - Push` host template to determine if a host is up or down.
If the host is down, the system will not send out service notifications for the particular host.

https://github.com/it-novum/openitcockpit-agent-go/wiki/Determining-the-host-status#push-mode


![agent_hostcheck_push](https://user-images.githubusercontent.com/9019992/219620016-4a42aaa4-1b5d-4af5-8a13-ce185ee47b74.png)

For Agents running in **pull mode**:
You could define a service dependency, but this is a lot of work.

![agent_servicedependency_defenition](https://user-images.githubusercontent.com/9019992/219616664-33501431-c58b-4bf5-9470-6aa06cc7e784.png)

![agent_servicedependency](https://user-images.githubusercontent.com/9019992/219616735-df229c54-f2ae-4eb9-b97a-67357ab50842.png)

However, the way simpler method is to use the `openITCOCKPIT Agent - Pull` host template instead.
If the host is down, the system will not send out service notifications for the particular host.

![agent_hostcheck](https://user-images.githubusercontent.com/9019992/219616921-d053934d-f25c-4f4b-ac0b-773f421dcd11.png)
