### ISSUE TITLE
Push Agent

### ISSUE THREAD

**Issue by Burotica** [it-novum/openITCOCKPIT#1123]
Hello,

I can't find detailed documentation for installing the openitcockpit agent in push mode.

So I created a host with the ip address: 0.0.0.0, in check-of-alive verification. I use the agent wizard, I choose Push.
So I have a conf file as follows:

```
[default]
address = 0.0.0.0
port = 3333
interval = 30
try-autossl = true
verbose = false
stacktrace = false
config-update-mode = false
auth = 
customchecks = 
temperature-fahrenheit = false
dockerstats = false
qemustats = false
cpustats = true
sensorstats = true
processstats = true
processstats-including-child-ids = false
netstats = true
diskstats = true
netio = true
diskio = true
winservices = true
systemdservices = true
wineventlog = true
alfrescostats = false
alfresco-jmxuser = monitorRole
alfresco-jmxpassword = change_asap
alfresco-jmxaddress = 0.0.0.0
alfresco-jmxport = 50500
alfresco-jmxpath = /alfresco/jmxrmi
alfresco-jmxquery = 
alfresco-javapath = /usr/bin/java

[oitc]
hostuuid = 7f422f67-9e68-42af-afc0-026cf4cc5bb3
url = https://openitcockpit.burotica.fr
apikey = a70ac35695f29d50e049a42a644c5c79339..............
interval = 60
enabled = true
```

LOG File :

```
2021-02-25 15:06:18,029; DEBUG; 939; Starting new HTTPS connection (1): openitcockpit.burotica.fr:443
2021-02-25 15:06:18,264; DEBUG; 433; https://openitcockpit.burotica.fr:443 "POST /agentconnector/updateCheckdata.json HTTP/1.1" 200 None
2021-02-25 15:06:18,279; INFO; 2328; <Response [200]>
2021-02-25 15:06:23,088; INFO; 457; Running default checks
2021-02-25 15:06:59,061; INFO; 457; Running default checks
```

It detects me well my Proc, Ethernet, Process ...
I add my Host, I update the configuration, I approve the SSL certificate.

But the HOST always remains unattached or down.

What am I doing wrong?

Debian 10 server, openITCockpit 4 installed according to tutorial.

Best regard

**Comment by nook24** [comment]
Hi @Burotica,

> It detects me well my Proc, Ethernet, Process ...

So far so good

The default check command for hosts is `check-host-alive` which will send a ping request to the host address. I assume that the host is not reachable from the openITCOCKPIT host because its operating in Push mode. You can set the host address to `127.0.0.1` to resolve this.

We are working on a new version of the Agent written in Go. It will be (hopefully) available as public beta in the next weeks and also contain a new host check which will force the host into `Down` state if the system did not receive any check results from a Push Agent for X minutes.

So stay tuned for openITCOCKPIT 4.2 🙂

**Comment by Burotica** [comment]
If I put 127.0.0.1 it puts the host UP well but the services are still UNKNOWN: No data received from agent.

However when I go to Agent overview and I download the JSON I do have a current file.

There must be something missing that I didn't understand

**Comment by nook24** [comment]
Have you trusted the Agent at `openITCOCKPIT Agent -> Agent Overview -> Untrusted agents` ?

**Comment by nook24** [comment]
Also unfortunately the Python Agent has some stability issues especially on Windows. For this reason we decided to rewrite the Agent from scratch as mentioned in my first post.

Due to the fact that you where able to create the services, I guess that the Agent has crashed on your system. Restarting the service `systemctl restart openitcockpit-agent` could help. At least for a while.

You can also update to the 2.x beta version of the Python Agent. This version was never released as a stable because we decided to step away from python but it resolved some issues. You can find all details about version 2.x in here: https://github.com/it-novum/openitcockpit-agent/issues/43

I would recommend you to subscribe [to this issue](https://github.com/it-novum/openitcockpit-agent/issues/43), it's where i frequently post status updates about the development process of the new Agent like my post from yesterday: https://github.com/it-novum/openitcockpit-agent/issues/43#issuecomment-786022977

As soon as version 3 of the Agent will be released the issues you are facing should be gone. Also the documentation about how to setup the Agent in **Push** or Pull mode got improved by a lot.

Best regards,

Daniel

**Comment by Burotica** [comment]
It works with agent 2.0.3, for info it's a MacOS 11.2.1. I will be testing on a Windows server 2019.

A big thank-you
