### ISSUE TITLE
Push monorinting device

### ISSUE THREAD

**Issue by Burotica** [it-novum/openITCOCKPIT#1127]
Hello,

Is it possible to monitor a device in Push?
If so, where can I find some documentation?
I imagine that we are using a PC host and that we have to make SNMP trap?

Thank you for your reply.

**Comment by nook24** [comment]
Hi @Burotica,

due to your previous issue #1123 i assume you are not talking about the Push Mode of the _openITCOCKPIT Monitoring Agent_.

> Is it possible to monitor a device in Push?

Short answers: Yes

The thing is, it depends on your use case.
If you want to monitor a device via SNMP Traps, I would suggest to grab yourself a [enterprise subscription](https://openitcockpit.io/#Subscription) and use the openITCOCKPIT SNMP Trap Module.

![Bildschirmfoto 2021-03-01 um 08 08 36](https://user-images.githubusercontent.com/9019992/109465649-d1348680-7a68-11eb-99eb-8badce00c136.png)

If you have a device that needs to push status updates for an host or service, you can use the [External Commands API](https://demo.openitcockpit.io/#!/nagios_module/cmd/index) for this. Especially the commands `PROCESS_HOST_CHECK_RESULT` and `PROCESS_SERVICE_CHECK_RESULT`.

The documentation is within the web interface for each command type:
![Bildschirmfoto 2021-03-01 um 08 06 33](https://user-images.githubusercontent.com/9019992/109465833-13f65e80-7a69-11eb-9f02-afbfd608837b.png)

Best regards,

Daniel
