### ISSUE TITLE
SudoServer error after logging into web ui through reverse proxy

### ISSUE THREAD

**Issue by prayingmantis287** [it-novum/openITCOCKPIT#1140]
I have a non-public facing nginx reverse proxy used for internal SSL to multiple server web applications. If I log into the OITC ui using its DNS name through the reverse proxy, I get the following two errors on every screen. The errors do not display when bypassing the reverse proxy and accessing the web interface via IP address.

`Attention! Could not connect to SudoServer. External commands may not work. Please try to reload this page.`

`Attention! Lost connection to SudoServer. External commands may not work. Please try to reload this page.`

![oitc_sudoserver_error](https://user-images.githubusercontent.com/39395422/111039376-cc25ee80-83fb-11eb-9bdd-09b6690e0a23.png)

I looked through various log files noted at [https://docs.it-novum.com/display/ODE/Logs](https://docs.it-novum.com/display/ODE/Logs), but there didn't appear to be any related entries. Also some of the log files did not exist.

I tried installing a new instance of OITC (using apt) on a fresh install of Debian 10, and the same behavior occurred. Are there any known issues using OITC through a reverse proxy?

**Comment by wx-db** [comment]
Hi, here with public reverse proxy, same issue and graph errors:

Installation on friday, no errors neither local or public proxied were displayed then, graphs working.

Returning today on monday same errors with sudoserver and no graphs are loaded, checks are being made.
Graphdata that has been collected and successfully displayed in the service graphs on friday are not visible anymore.

The sudoserver error is not showing while accessing with the localip.

Total checks are (for testing purposes) 3 external Agents with pushing configuration.

Seems that the openitcockpit-graphing service keeps failing, after restarting its running until trying to display any graphs:

Syslog is full of:

Mar 15 11:27:32 ossm statusengine-worker[670]: Graphite error: Could not connect: [111] Connection refused
Mar 15 11:27:37 ossm StatusengineWorker.php[559]: statusengine-worker[670]: Graphite error: Could not connect: [111] Connection refused
Mar 15 11:27:37 ossm statusengine-worker[670]: Graphite error: Could not connect: [111] Connection refused
Mar 15 11:27:37 ossm StatusengineWorker.php[559]: statusengine-worker[670]: Graphite error: Could not connect: [111] Connection refused
Mar 15 11:27:37 ossm statusengine-worker[670]: Graphite error: Could not connect: [111] Connection refused

Service status:

 openitcockpit-graphing.service - Graphing Backend for openITCOCKPIT
   Loaded: loaded (/lib/systemd/system/openitcockpit-graphing.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-03-15 11:28:38 CET; 8s ago
  Process: 17701 ExecStartPre=/usr/bin/find /var/lib/graphite/whisper/carbon/relays -mmin +120 -delete (code=exited, status=1/FAILURE)
  Process: 17702 ExecStart=/usr/bin/docker-compose up --remove-orphans --abort-on-container-exit --no-build --force-recreate (code=exited, status=1/FAILURE)
 Main PID: 17702 (code=exited, status=1/FAILURE)

**Comment by nook24** [comment]
Hi,

The SudoServer uses WebSockets and therefore requires a (kind of) special configuration of the reverse proxy. 
I added two examples to the documentation, one for Nginx and one for Apache2.
https://docs.it-novum.com/display/ODE/openITCOCKPIT+behind+a+reverse+proxy

@prayingmantis287
I also updated the overview of the log files.

@wx-db
For me it looks like that you are facing two different issues:
1. Your issue with the reverse proxy can be resolved by using the example configurations I posted above.
2. The `openitcockpit-graphing` backend has nothing to do with the reverse proxy. Most likely your system ran out of memory or so. The documentation for the graphing backend can be found here: https://docs.it-novum.com/display/ODE/Graphing+Backend

If `systemctl restart openitcockpit-graphing` is not going to resolve your issue, please create a separate GitHub issue for this.

Regards,
Daniel

**Comment by wx-db** [comment]
Hi,

yes 2 different issues, the reverse proxy sudoserver error seems solved with the additional location:

location / {
  proxy_pass https://xxx/;
  include proxy_params;
  }
location ~ ^/(sudo_server|push_notifications|nsta)$ {
  proxy_pass https://xxx;
  include proxy_params;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  }

for the 2nd issue I will reinstall openitcockpit, there seems to be some missing config files /etc/openitcockpit/grafana/ though they are located in /opt/openitc/etc/grafana if the problem persists I will open another issue.

Thanks!

Danke, schnell und promt wie immer ;)

Servus David

**Comment by prayingmantis287** [comment]
I can confirm the Nginx config works like a charm. Thanks for the fast resolution nook24.

**Comment by nook24** [comment]
Perfect 👍
