### ISSUE TITLE
API: DISABLE_SVC_CHECK not working with Agent

### ISSUE THREAD

**Issue by TB1234** [it-novum/openITCOCKPIT#1195]
Environment: multiple servers with Debian/Ubuntu/ArchLinux and latest OpenITCOCKPIT-Agent (could also reprocude with old 3.0.5 Agent), services with pull

Case: in case of high load of backup I want to disable some service checks on specific machines. For this I call the API with DISABLE_SVC_CHECK via curl before the backup and ENABLE_SVC_CHECK after the backup via curl. This does not work for services, which are monitored via the Agent. I still got notifications of high CPU load or high network load.

My call:
curl -X POST -k -H "Content-Type: application/json" https://www.my.host/nagios_module/cmd/submit.json?apikey=<apikey> -d '{"command":"DISABLE_SVC_CHECK","hostUuid":"host-u-uid","serviceUuid":"service-u-uid"}'

The API-Call for activiating/deactiving the flapping detection works fine. So my call an also my ids are right.

**Comment by nook24** [comment]
For Agents running in Pull-Mode you need to disable the `OITC_AGENT_ACTIVE` service. This service queries the openITCOCKPIT Monitoring Agent, evaluate all results and pass the result to the different services like CPU Load, Memory Usage etc.

I would recommend to create a recurring downtime (maintenance) for the particular hosts instead of disabling the monitoring. With a downtime the system will still collect metrics and evaluation checks but don't' send notifications about any issues. 

![Bildschirmfoto 2021-07-13 um 11 02 54](https://user-images.githubusercontent.com/9019992/125424072-6bf7b6f9-7a6a-452c-a374-21b72b584beb.png)


https://demo.openitcockpit.io/#!/systemdowntimes/addHostdowntime

**Comment by TB1234** [comment]
But if I disable OITC_AGENT_ACTIVE, there will not system activity be logged any more. Or I am false?

I cannot create a recurring downtime because I do not know the time the system need for backups. If customers create a lot of files, my backup need more time.

**Comment by nook24** [comment]
What exactly do you want to achieve?

**Comment by TB1234** [comment]
I want to disable the notifications/warnings for specific services for a specific time period. I do not know the time period before so I cannot shedule it via a recurring downtime but I can call the API before and after the process to start and stop it...

**Comment by nook24** [comment]
You can use the `SCHEDULE_HOST_DOWNTIME` / `SCHEDULE_SVC_DOWNTIME` commands to schedule a downtime when the backup starts.
When the backup is complete, you can query the API to get the current downtime id:
```
https://demo.openitcockpit.io/services/browser/<serviceuuid or service id>.json?apikey=<api key>
```

Result (stripped)
```js
"downtime": {
    "authorName": "Demo User",

    "internalDowntimeId": 10,
  },
```

With the internalDowntimeId you can call `DEL_HOST_DOWNTIME` or `DEL_SVC_DOWNTIME` to remove the downtime.

**Comment by TB1234** [comment]
But I need also a duration and start/stop time for `SCHEDULE_SVC_DOWNTIME`. So I need to fake it with a very long time or have to risk a wrong notification...

**Comment by nook24** [comment]
You can also disable the notifications `DISABLE_SVC_NOTIFICATIONS` 🤷‍♂️

**Comment by TB1234** [comment]
That seems to be a solutions for my problem. Thanks!
