### ISSUE TITLE
Graphite whisper files fill disk

### ISSUE THREAD

**Issue by enx1998** [it-novum/openITCOCKPIT#1329]
Hi,
after adding the precesses service for all running processes to a host, graphite whisper started filling up all the free disk space. I have tried removing the directories that contain the whisper files, but they are regenerated filling up all the free disk space again. To stop graphite filling up my disk I had to stop the openitcockpit-graphing service. After stopping it I deleted the host that caused the problem, but the whisper files continue to be generated after restarting the openitcockpit-graphing service.

How can I stop the openitcockpit-graphing service generating such whisper files?

Thanks ENx

**Comment by enx1998** [comment]
Hi @nook24,
thanks for your reply, I will certainly change these settings, but currently my problem is that whisper generates graphing data for a deleted service when it starts up even though I have previously deleted it.
Is there a method to avoid generating such files?

Thanks, ENx

**Comment by nook24** [comment]
You probably need to refresh your monitoring configuration. Otherwise the service is delete and not visible in the interface anymore, but still known to the backend systems.

1. Delete the Service via the web interface
2. [Refresh the monitoring configuration](https://docs.openitcockpit.io/en/beginners/create-first-host/#updating-the-monitoring-configuration)
3. Than delete the .wsp file on filesystem

Due to an bug, openITCOCKPIT is not deleting old .wsp files automatically.
