### ISSUE TITLE
Problem checkmk

### ISSUE THREAD

**Issue by juniorkalvin7** [it-novum/openITCOCKPIT#1390]
Exception: Class 'App\itnovum\openITCOCKPIT\Monitoring\Naemon\IllegalCharacters' not found
In [/opt/openitc/frontend/plugins/CheckmkModule/src/Command/CheckmkNagiosExportCommand.php, line 192]

2022-07-22 10:22:14 Error: [Error] Class 'App\itnovum\openITCOCKPIT\Monitoring\Naemon\IllegalCharacters' not found in /opt/openitc/frontend/plugins/CheckmkModule/src/Command/CheckmkNagiosExportCommand.php on line 192
Stack Trace:
- /opt/openitc/frontend/plugins/CheckmkModule/src/Command/CheckmkNagiosExportCommand.php:113
- /opt/openitc/frontend/plugins/TelegramModule/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /opt/openitc/frontend/bin/cake.php:12

**Comment by nook24** [comment]
Is this a follow up of https://github.com/it-novum/openITCOCKPIT/issues/1388 ? You are probably ending up with this error, because not all components have been updated to the latest version.

Please run as `root` user
```
apt-get update
apt-get dist-upgrade
```
to update all packages and dependencies. Keep track of the process and check for any errors.

**Comment by nook24** [comment]
🤷‍♂️
