### ISSUE TITLE
Containers overview and Sub container count wrong

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1525]
**Describe the bug**
The Container Dropdown (containers/index) shows a wrong parent-child tree. Some Containers are under the wrong parent.
This leads also to a wrong sub Container count when showing the tree. But in the tree view, the parent-child are displayed correctly.
The containers (ser, app and isa) have the same parent "l2". In the Dropdown "app" is shown as a child from "isa"

**To Reproduce**
I have no idea how to reproduce

**Expected behavior**
Container Dropdown should show the right parent-child tree.
Sub containers should be counted correct

**Screenshots**
![dropdown](https://github.com/it-novum/openITCOCKPIT/assets/4117419/01e7049d-0c15-4b0e-881a-5fdbf42fc27c)
![tree](https://github.com/it-novum/openITCOCKPIT/assets/4117419/f27daf04-b9ea-4ed7-96de-b53b1d381932)

**Versions**
* openITCOKPIT Server Version: 4.6.5
*  NAME="Red Hat Enterprise Linux"
  VERSION="8.8 (Ootpa)"

**Additional context**

**Comment by nook24** [comment]
Hi @kbilev 

Did you modified the table `containers` manually somehow?
Unfortunately I was unable to replicate this in our [demo environment.](https://demo.openitcockpit.io)

![grafik](https://github.com/it-novum/openITCOCKPIT/assets/9019992/8133a66a-9e9b-4285-9f99-234dda9d8809)


To debug this, a SQL dump of the containers table would be required. 
Please feel free to rename sensitive information into "Tenant A" or "Hostgroup 1" for example.

You mentioned that your system is running on RHEL, which is only available for Enterprise customers. It would be probably better to contact the enterprise support so you do not have to upload any SQL dumps to public GitHub.

**Comment by nook24** [comment]
Got handed over to commercial support.

**Comment by nook24** [comment]
Hi @kbilev
we have done some further investigations and found the root course of the issue. The issue was probably caused by the fact, that the [Tree Behavior of the CakePHP framework](https://book.cakephp.org/4/en/orm/behaviors/tree.html) is not safe when concurrency is used.

When multiple connections try to update the container tree at the same time, the values for `lft` and `rght` will be get calculated wrong by the framework.

To resolve this issue, we added a write lock to the containers table, that only one operation can be done at the same time. 

We are also working on an check and repair script, so that all users of openITCOCKPIT will have an easy method to check if the container tree has orphaned containers. 

Pull Request: https://github.com/it-novum/openITCOCKPIT/pull/1529

We will also write a detailed blog post about the issue and how to resolve it, once the PR is merged.

**Comment by kbilev** [comment]
Hello @nook24 ,

thanks for the update.
Probably this was the issue, as we may have added and changed/renamed some containers at the same time

Best Regards,
Kevin

**Comment by nook24** [comment]
openITCOCKPIT 4.6.6 contains a patch to avoid issues like this.
It also has a check and repair command for the container tree, please see the blog post for more information: https://openitcockpit.io/2023/2023/07/19/openitcockpit-4-6-6-released/

**Comment by kbilev** [comment]
Thanks for the bugfix and the check command.
I checked our instance, no orphaned containers found anymore

BR,
Kevin
