### ISSUE TITLE
push nrpe client external does not work 

### ISSUE THREAD

**Issue by juniorkalvin7** [it-novum/openITCOCKPIT#1597]
I have an agent outside the network where the server is located, how would the client communicate with the server via nrpe?

![Captura de Tela 2023-11-09 às 08 38 10](https://github.com/it-novum/openITCOCKPIT/assets/16207790/a7f86cce-0e26-493f-a3b1-59ede318d44a)

**Comment by nook24** [comment]
In that case, you need to use something else than NRPE, because NRPE is operating in Pull Mode. That means that the openITCOCKPIT Server establishes the connection to the client. (Server -> Client)

If I understand you right, you are probably looking for something that is operating in push mode. So the that the client connects to the openITCOCKPIT server to submit check results. (Client -> Server)
Have you already took a look at our Agent? It should be exactly what you are looking for:
https://docs.openitcockpit.io/en/beginners/openitcockpit-agent/#push-mode

You can also use it to execute custom check plugins like you did with NRPE:
https://github.com/it-novum/openitcockpit-agent-go/wiki/Define-custom-checks

**Comment by nook24** [comment]
Closed due to inactivity
