### ISSUE TITLE
Hosts not searchable

### ISSUE THREAD

**Issue by zrhck** [it-novum/openITCOCKPIT#749]
From i-doit imported hosts are sporadically not searchable. Though you can find them with their ID in hosts list and within the database.
 Re-importing didn't help. Sometimes previously working hosts become unsearchable too after re-importing.

**Comment by nook24** [comment]
Hi @zrhck, thanks for your feedback.

Does this hosts just get vanished, or does this only happen if your refresh your monitoring configuration?
![bildschirmfoto 2018-01-22 um 11 11 47](https://user-images.githubusercontent.com/9019992/35215740-87d6dee2-ff65-11e7-83a6-dad4ea11ef7f.png)

After an restart of the monitoring backend (Naemon or Nagios), all objects needs to be reimported to the database. You can follow up this process at "Administration -> Debuggin -> Queuing engine":
![bildschirmfoto 2018-01-22 um 11 13 10](https://user-images.githubusercontent.com/9019992/35215844-e239d0ba-ff65-11e7-822a-4048de9924a4.png)

As long as there are objects left in the queue `statusngin_objects` they are may be hidden from the lists. Depending on the size of your system, processing this queue should not take longer than a few seconds.

**Comment by zrhck** [comment]
Hi @nook24 ,

refreshing the configuration does not make a difference. I imported two hosts from i-doit, both are browsable (like https://127.0.0.1/hosts/browser/648) but not findable through the search. Just to clarify things :)
![image](https://user-images.githubusercontent.com/34365002/35217029-087a7ee2-ff6a-11e7-97fe-a29930690102.png)
![image](https://user-images.githubusercontent.com/34365002/35217130-66beb446-ff6a-11e7-9bba-f67b401abf28.png)

regards

**Comment by zrhck** [comment]
Hi @nook24,

sorry i forgot to mention that everything is working fine except above.
![image](https://user-images.githubusercontent.com/34365002/35218047-8906c6c6-ff6d-11e7-8bc9-6166b908f749.png)

**Comment by nook24** [comment]
Hi @zrhck,
i guess we found the issue. Inside of the i-doit import, the `hosttemplate_id` was used for the `container_id`. So, i guess all hosts where imported into an "Container Id", of an Hosttemplate.
![bildschirmfoto 2018-01-22 um 12 53 24](https://user-images.githubusercontent.com/9019992/35221661-3d10128c-ff7b-11e7-957b-6d0f138a5243.png)

All permissions of the interface are based on the "container_id", so due to the wrong id, the frontend guess you don't have permissions on the given host, so the host is not listed.

So, i guess your user is an "global admin", which is marked with the yellow trophy:
![bildschirmfoto 2018-01-22 um 13 22 21](https://user-images.githubusercontent.com/9019992/35221333-085ba57a-ff7a-11e7-9c31-e260ec6ab8db.png)

You can still browse to the host via the URL, because permission checks are disabled for global admins (they have access to all objects), but you are not able to find the host, because the lists are always filtered by permissions.

First of all, we should check, if this is really the root cause of the issue. The following sql statement, will select all hosts, that are linked to an non existing container.
````SQL
select hosts.id, hosts.name, hosts_to_containers.container_id, containers.id from hosts
inner join hosts_to_containers on hosts.id = hosts_to_containers.host_id
left join containers on hosts_to_containers.container_id = containers.id
where containers.id IS NULL
````
You can use the MySQL CLI to execute the statement, or phpMyAdmin (https://127.0.0.1/phpmyadmin)  The SQL credentials are stored in the file `/etc/openitcockpit/mysql.cnf`.

The SQL statement will list you all hosts, that are linked to an non existing container, like in this example:
![bildschirmfoto 2018-01-22 um 13 38 48](https://user-images.githubusercontent.com/9019992/35221570-ef5033ce-ff7a-11e7-829f-de6c19b3228a.png)

If the result is not empty, than you ran exactly into this issue :(

Please let us know, if the query is going to find some hosts. If yes, we will try to create an query to move all the hosts into a container of your choice :)

**Comment by zrhck** [comment]
Hi @nook24 

thank you for your reply. The query delivers an empty set:
![image](https://user-images.githubusercontent.com/34365002/35222434-29342d4a-ff7e-11e7-817e-b207080fe09f.png)

**Comment by nook24** [comment]
Hmm, are you able to edit the host via the URL? `https://127.0.0.1/hosts/edit/648`

**Comment by zrhck** [comment]
Yes, absolutely

**Comment by nook24** [comment]
Can you please join our pulic IRC channel?
http://webchat.freenode.net/?channels=openitcockpit
I guess its better to find the root cause...

**Comment by zrhck** [comment]
Sure

**Comment by nook24** [comment]
As mentioned, the issue was caused by an wrong container_id. To resolve the issue, it was required to call the Edit action via the url `/hosts/edit/13` and press on save.

With Version 3.3 the issue will be resolved.
