### ISSUE TITLE
Email sending to info email despite removing it

### ISSUE THREAD

**Issue by osirusrising** [it-novum/openITCOCKPIT#800]
Configured the email.php to send to 127.0.0.1 as instructed using Postfix, get notifications partially if i push the test, but normal notifications don't come thru.   Also continued to get emails postmaster failed to info@openitcockpit.local.localhost always as that is a contact in the system.  So I removed that contact entirely and the system is still sending notifications to that email address and the contact is gone.  Please fix or advise.

**Comment by nook24** [comment]
Hi @osirusrising, the `info` contact use as default email address `openitcockpit@localhost.local`. So you should change the address first.

When every you change the monitoring configuration, you need to refresh the monitoring configuration:
![bildschirmfoto 2018-04-26 um 09 05 44](https://user-images.githubusercontent.com/9019992/39290959-9d5802e4-4931-11e8-8019-8ea4d4d67a86.png)
![bildschirmfoto 2018-04-26 um 09 19 57](https://user-images.githubusercontent.com/9019992/39291356-059ffac2-4933-11e8-8013-af8f1796e1aa.png)

We decided to not automatically reload the monitoring engine whenever  a configuration change occur.
Otherwise systems with many users would only restart the monitoring engine instead of scheduling checks

Also make sure, that the user `nagios` is able to read the file `/etc/openitcockpit/app/Config/email.php`
````
$ ls -la /etc/openitcockpit/app/Config/email.php
-rw-r--r-- 1 www-data www-data 959 Sep 29  2017 /etc/openitcockpit/app/Config/email.php
````

**Comment by nook24** [comment]
Feel free to open a new issue if you run into any future problems.
