### ISSUE TITLE
Feature request: Anonymous access to status maps

### ISSUE THREAD

**Issue by farosch** [it-novum/openITCOCKPIT#821]
I would really lova an anonymous access to some kind of status map, so that I can embed it onto another homepage. The goal would be to provide something similar to https://www.apple.com/de/support/systemstatus/ for our users so that they can take a look themselves at the system status without having to ask the IT department.

**Comment by nook24** [comment]
I like the idea. At the moment anonymous login is unfortunately not possible, because most of the openITCOCKPIT instances hold sensitive information.

How ever, you could use our API to script this real quick. For example you could use an "Auto Map" for this task, and hack a PHP, JavaScript, Python, `<insert favorite language>` snippet to query the required information from the openITCOCKPIT API and insert a table to your website.

You can create a own user for this case, and only grant permissions to "Auto Map" or other API Endpoints you want to use. Than you can access the JSON API with an API Key like described in our last blog post: https://openitcockpit.io/2018/05/30/openitcockpit-3-4-2-released/

Example of the Auto Map JSON Data:
![bildschirmfoto 2018-06-25 um 09 33 23](https://user-images.githubusercontent.com/9019992/41853599-6e84a166-788e-11e8-9183-fcdc9170dfa9.png)

**Comment by nook24** [comment]
openITCOCKPIT 4.7.0 has added `Status pages` as a new feature. That's exactly what you are looking for i guess :)
https://docs.openitcockpit.io/en/reporting/reporting/#status-pages
