### ISSUE TITLE
Removing Mariadb

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#831]
The normal installation process asks for mysql to be installed, which removes mariadb from the system if it is already installed. Ideally the installation process should not remove mariadb or compatible database server if already installed.

**Comment by Tampa** [comment]
Probably worth noting that past some minor issues, missing menu, broken auto refresh, openitcockpit runs on mariadb just fine, I manually force installed the packages, may have missed something. Would be nice if you could set mariadb as alternative for mysql in the normal install script.

**Comment by Tampa** [comment]
An issue or two later and I can say that installing manually using dpkg, skipping mysql installation in favor for mariadb, does produce the same usable system. I mean, duh, mariadb is basically the same thing or close enough for direct compatibility. So I would say best to remove the database dependency entirely and request the user either install mysql or mariadb before starting the openitcockpit setup.

**Comment by nook24** [comment]
Hi @Tampa, at the moment we use the default package for `mysql-server`. For Ubuntu Trusty, Xenia, Bionic and Debian 8 it's MySQL from Oracle.

If you want to go with MariaDB, you can install openITCOCKPIT on Debian 9 (Stretch). The default for the package `mysql-server` is `10.1.26-MariaDB`. So every openITCOCKPIT running on Debian 9 will use MariaDB out of the box.

> So I would say best to remove the database dependency entirely and request the user either install mysql or mariadb before starting the openitcockpit setup.

We like to keep the installation process as simple as possible. This also could cause some trouble on updates... We will put a ticket to our backlog to check, if it is possible to depend on mysql or mariadb in the packages.

**Comment by Tampa** [comment]
Add a -nosql flag or something to the installation script then to skip the mysql dependency, that way at least more advanced users like me don't have to go through manually installing every single package and dependency, because that is way more work in comparison.

**Comment by nook24** [comment]
Unfortunately we can not work with arguments in this case.
How ever, as already mentioned we put it in our backlog and we will check this.

I guess the only possible way would be something like this solution:
openITCOCKPIT install will depend on MySQL or MariaDB. So if you run the `apt-get install openitcockpit{,-common,-naemon,-statusengine-naemon,-message}
` command on a blank system, it will use the default mysql server of the distribution like now.

Due to the or condition, it would be possible, that the user install MariaDB in the first step, and install openITCOCKPIT in the next step. Than openITCOCKPIT will use MariaDB. This should be possible...

If you want to go with MariaDB for now, and you want to have a good time (be update save, etc.), I really would recommend you to use Debian 9 at the moment.

**Comment by Tampa** [comment]
I edited the apt status to reflect the mariadb requirement, if I read it correctly so long as I don't purge the apt cache that requirement should stick, though since I manually install updates I will review that each time.

The proposed conditional for the installation would satisfy my needs and likely those of anyone who wishes to run mariadb.

**Comment by Tampa** [comment]
Do I really have to go out of my way to create my own apt repo and edit the install scripts just to change a downright drop-in replacement? You talk about testing that needs to be done in order to verify, well, what exactly? What possible reason is there to forcefully use a specific database provider when every other software I have ever used had not a single issue switching to MariaDB or, in fact, resolved itself from issues it had while using MySQL or MSSQL. Even if it, for some strange unthinkable reason, encountered a problem, I highly doubt you'll not find the solution within minutes. 6 years I been using it, no issues. Not enough? How about this then: https://en.wikipedia.org/wiki/MariaDB#Prominent_users There is a reason for that.

**Comment by nook24** [comment]
Hi @Tampa ,
we are just going with the default of the used linux distribution at the moment. **It is not a political statement. We don't prefer MySQL over MariaDB or something like that!**

> You talk about testing that needs to be done in order to verify, well, what exactly?

Yes, we test our software. This is always an ongoing process and never stops. Especially changes done to the debian packages needs to be tested super intensive from our side. Imagine hundred of systems (maybe with unattended updates enabled) are running into issues due to a wrong change in the dependency tree.

We also added this as a Feature Request to our internal ticketing system. So you will be the first one we notice, as soon as we support MariaDB on Ubuntu. But, supporting MariaDB (on Ubuntu) has not the highest priority. We will add this if we need to make major changes in the debian package files - or if we have time for this.

If MariaDB has top priority for you, you have three possible solutions:

1.  Install openITCOCKPIT on Debian. It will use MariaDB out of the box. No effort. No trouble. Just fun.
2. Contact the company behind openITCOCKPIT and ask for a quote: https://it-novum.com/en/it-service-management/openitcockpit/
3. Patch it yourself.

**Comment by Tampa** [comment]
You still haven't answered my question as to what testing you do, I was going to offer doing said tests for you and provide the results, even though running openitcockpit for over a year now on a weekly patched system that has not broken down yet. If you actually want community support and help, hence open source, then provide a way for us to help you with such things.

Guess I will have to patch this myself then come next release, but don't expect me to provide said change if you can't even tell me what you are so afraid of breaking.

**Comment by nook24** [comment]
Hi @Tampa,
I added MariaDB to the current nightly version (3.6.2-2ubuntu18.04~201902130821 Ubuntu Bionic only) and first tests are looking good. MySQL will be still the default. You need to make sure that the packages `mariadb-server mariadb-client` are installed first.

Load the nightly repository:
````
echo 'deb https://packages.openitcockpit.com/repositories/bionic nightly main' > /etc/apt/sources.list.d/openitcockpit.list
apt-get update
````

Install MariaDB
````
apt-get install mariadb-server mariadb-client
````

Install openITCOCKPIT
````
apt-get install openitcockpit{,-common,-naemon,-statusengine-naemon,-message}
````

Please come back to us if you find any issues.

**Comment by Tampa** [comment]
The machine I do testing on still runs on 16, I added it anyways(cause why not).

`The following packages will be REMOVED:
  naemon naemon-thruk nginx-full thruk thruk-base thruk-plugin-reporting
`
I assume you now ship a custom version of naemon? Why is nginx being removed though?

**Comment by Tampa** [comment]
After a lot of pain getting the old version cleanly removed the new version installed properly now. Gotta say the install scripts don't handle partial failures of any one package all that well. So far no other issues reported, even grafana eventually decided to work.

The install and deinstall scripts are not particularly "smart" when encountering failures. If files already exist, connections to docker fail, services not starting. It seems the only way to install everything is doing so in one go, when one package fails, resuming install seems almost impossible. This could be due to packages all depending on each other instead of having a hierarchy from the main->modules->config.

The additions made using the docker containers are not fun from an administration standpoint. Debugging their failures is ever harder due to docker hiding them. I get it, it's easy to just spin up a docker image and stuff things in there than configure them bare-metal, but this all adds bloat to the system. The dependency tree and additional services have grown to a scope that makes is quite the task to configure monitoring for the monitoring, especially when recovery from crashed docker containers seems to only be possible by rebooting the entire server.

Again, I get it, it makes it easier in some way, but the points of failure are just increasing left and right and the benefit, while looking pretty, is not as great as it seems. Just my two cents on the matter.

**Comment by nook24** [comment]
> The machine I do testing on still runs on 16, I added it anyways(cause why not).

This really doesn't sounds like the best idea...

> The following packages will be REMOVED: `naemon naemon-thruk nginx-full thruk thruk-base thruk-plugin-reporting`

Except Nginx these are non openITCOCKPIT related packages. openITCOCKPIT use an own package for Naemon (or Nagios): `openitcockpit-naemon` or `openitcockpit-nagios`

> The install and deinstall scripts are not particularly "smart" when encountering failures.

That's true. All our scripts are going to stop if an unexpected error occurred. This helps to resolve the issue step by step. Otherwise you may be wouldn't even notice that something went wrong.

How ever. I guess you already patched a lot around on your system. So i'm not surprised that things are running into issues^^

> recovery from crashed docker containers seems to only be possible by rebooting the entire server.

All Docker containers are controlled by `docker-compose` and `systemd` More information about the containers and how to access the log files and stuff are in the documentation: https://docs.it-novum.com/display/ODE/Graphing+Backend

When everything is clean again and with the support for MariaDB updates should become much more easier for you in the future.
You can also use the `Backup / Restore` feature to migrate you existing configuration to a new installation.
