### ISSUE TITLE
Host Notifications showing UUID instead of Hostname

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#867]
![hostnotification](https://user-images.githubusercontent.com/2485980/47423091-8150a100-d784-11e8-9629-50a0a4a8aef1.jpg)

As you can see, in Host notifications $HOSTNAME$ is filled with the uuid instead of the hostname.

**Comment by nook24** [comment]
Hi @Tweak90,
it is recommended to use the default notification commands of openITCOCKPIT, which resolve this issue: https://openitcockpit.io/beginners/7-setup-email-notifications/
With `--format` the email format can be set to `text`, `html` or `both`(default).

How every, for custom commands you can use one of the following options:
1) Pass `$HOSTDISPLAYNAME$` (instead of `$HOSTNAME$`) and `$SERVICEDISPLAYNAME$` (instead of `$SERVICEDESC$`), but this could run into escaping issues if your names contain special characters like & or $.
2) Look Up the proper host- and services names in the mysql database. `UUID` is indexed so this is quite fast.

Hope this helps.
