### ISSUE TITLE
Plugin ConfigGenerator not found

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#902]
Installing via apt through manual download and install of packages to circumvent mysql requirement in favor of mariadb. Latest version fails to update due to following error. Are additional packages required or other steps needed to upgrade to the latest?

`Setting up openitcockpit-message (3.6.0-1ubuntu16.04) ...
Error: Plugin ConfigGenerator could not be found.
#0 /usr/share/openitcockpit/lib/Cake/Core/App.php(227): CakePlugin::path('ConfigGenerator')
#1 /usr/share/openitcockpit/lib/Cake/Core/App.php(549): App::path('Console/Command', 'ConfigGenerator')
#2 [internal function]: App::load('ConfigGenerator...')
#3 [internal function]: spl_autoload_call('ConfigGenerator...')
#4 /usr/share/openitcockpit/lib/Cake/Console/ShellDispatcher.php(264): class_exists('ConfigGenerator...')
#5 /usr/share/openitcockpit/lib/Cake/Console/ShellDispatcher.php(210): ShellDispatcher->_getShell('config_generato...')
#6 /usr/share/openitcockpit/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /usr/share/openitcockpit/app/Console/cake.php(33): ShellDispatcher::run(Array)
#8 {main}
dpkg: error processing package openitcockpit-message (--configure):
 subprocess installed post-installation script returned error exit status 244
Errors were encountered while processing:
 openitcockpit-message
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by nook24** [comment]
Good morning @Tampa,
The `ConfigGenerator` is a essential core component of openITCOCKPIT 3.6. It is not a Plugin because openITCOCKPIT can't work without this component.

In fact that you are getting an error like this `Error: Plugin ConfigGenerator` I would guess there was an error while install the new `openitcockpit-common_3.6.0-1ubuntu16.04_amd64.deb`.

At the moment we don't support using MariaDB on Ubuntu systems. As already mentioned in https://github.com/it-novum/openITCOCKPIT/issues/831#issuecomment-401759983
I highly recommend to install openITCOCKPIT on Debian Stretch if you want/need to use MariaDB.
On Debian Stretch MariaDB is used by default. **No additional changes required.**

You can also easily migrate your system by creating a dump of your current database.

**Comment by Tampa** [comment]
"I highly recommend to install openITCOCKPIT on Debian Stretch" aka "change your entire OS" is not really an option that should be recommended when everything else works perfectly fine. Give me a critical reason why supporting or even just allowing MariaDB on Ubuntu is such a grave mistake.
