### ISSUE TITLE
Feature request: Copy Service Templates easyier

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#970]
It would be easyier if you can copy the Service Templates
![grafik](https://user-images.githubusercontent.com/16563785/67687383-86988b00-f998-11e9-8613-776dd37c1423.png)
here

and if you can input changes in the following site (/servicetemplates/edit/id of new service)

**Comment by nook24** [comment]
I created an UX/UI Improvement ticket to also add the "Copy" button to the Drop-down menus of objects.

However, it is not possible to open the suggested URL `/servicetemplates/edit/<id>` directly because you can copy two or more service templates with the same action.

To make the copy function of services templates more useful, we added in Version 4 the option to change the check command and parameters during the copy process:
![servicetemplates_copy_v4](https://user-images.githubusercontent.com/9019992/67691479-f4e04c00-f99e-11e9-80b1-2abcec93c9f5.png)

**Comment by Terminator81** [comment]
sounds great.....is there a timeline when v4 will be released?

**Comment by nook24** [comment]
Copy for host and service templates got implemented into the final version of openITCOCKPIT 4 so i will close this :)

![Screenshot_2020-09-23 Monitoring powered by openITCOCKPIT](https://user-images.githubusercontent.com/9019992/93979431-9de52180-fd7d-11ea-8449-2cc5624bd417.png)
