### ISSUE TITLE
Kein Zugriff mehr nach Update 3.6.1 auf 3.7.2

### ISSUE THREAD

**Issue by Haertie** [it-novum/openITCOCKPIT#976]
Ich hab openitCockpit heute von der Version 3.6.1 auf die 3.7.2 auf einem Ubuntu 16.04 per apt dist-grade (also ganz normal) gebracht. Ich bekomme auch weiter fleißig Mails vom System über "defekte" Dienste.
Leider ist es mir unmöglich auf die Seite zuzugreifen. Der Browser bleibt einfach weiß, es passiert gar nichts. Nach einer Ewigkeit kommt ein 504 vom NGinx. In den üblichen Logfiles /var/log/nginx/cake/error.log /var/log/php7.0-fpm.log finde ich keine fehler. Im Errorlog vom Nginx im Debugmodus kommt am ende ein 499-Fehler. 
openitcockpit-update --roles-admin ----- hab ich ausgeführt. Einzigster Fehler ist:

Set new user group permissions...    Notice **Error**: Undefined index: Aco in [/usr/share/openitcockpit/app/Console/Command/SetPermissionsShell.php, line 108]

Warning Error: Invalid argument supplied for foreach() in [/usr/share/openitcockpit/app/Console/Command/SetPermissionsShell.php, line 108]

Allerdings kam der Fehler schon immer. Ich bin eigentlich nicht der Typ der bei sowas fragt. Ich suche meist selbst nach Lösungen, aber dieses Problem ist hartnäckig. Ich sitze hier schon 2 Tage dran und Google ist mein Freund. Kennt jemand das Problem?

Vielen Dank

**Comment by nook24** [comment]
The issue was caused by the updated LDAP connect which was implemented with openITCOCKPIT 3.7.1 to use startTLS:
https://github.com/it-novum/openITCOCKPIT/commit/c7f0265c14e49dd2f312db315d0424920f657dba

Looks like the LDAP Server is misconfigured or the old library which is used for php <= 7.2 is having some issues.
You could try to update your system to use php 7.2 to use the new LDAP implementation.

As workaround, you can disable TLS for LDAP:
```SQL
UPDATE systemsettings SET `value`='0' WHERE `key`='FRONTEND.LDAP.USE_TLS';
```

**Comment by Haertie** [comment]
Super. Hat funktioniert. Problem gelöst.

Danke
