### ISSUE TITLE
Export and import of configuration objects

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#978]
Backups are nice and doing manual ones of the DB also helps, but re-deploying entire systems it gets frustrating to enter all data by hand.

An entry via either xml or csv would be nice to have. Ability to load in templates, commands, services, hosts, escalation rules, contacts etc and of course exporting them too.

For example I have a service template that I use to make specific services, however each one needs a change to the expert settings to supply two arguments and I want to rename them so I know which one is which. This I currently have to do manually and with over 200 of those entry consumes a good two hours, some systems I deployed had over 5000 of such services.

**Comment by nook24** [comment]
Due to this issue is open for a while, I would like to add a quick update on this.
Exporting and importing configuration objects like commands, host and service templates, contacts, time periods and so on is a complex feature request. 

To export the data isn't that hard. The challenging part would be the import procedure. While importing the data the system has to check all object permissions (containers), if all dependencies are met (exists the time period? exists the command? etc) and also resolve naming conflicts. There's probably more to consider. 

Unfortunately due to the complexity we have no plans to implement a feature like this any time soon.

In case you are interested in a collaboration on this, feel free to contact our commercial support: https://openitcockpit.io/community/

**Comment by valiunas** [comment]
Daniel,  if you change your mind,  the single case of importing serviceCheckTemplates associated with the root container would be a huge benefit for those with multiple large masters to try to keep in sync.  Would the ability to add checks individually via the API with the responsibility of setting the proper containers and timePeriods and such left to the user be an easier lift?

**Comment by nook24** [comment]
Hi @valiunas I hope you are doing well.

Even by restricting the import only to objects in the root container, service templates are one of the objects with the most dependencies, such as commands, command arguments, time periods, contacts, contact groups and event handlers.

There need to be done a clear definition of what should happen if objects already exists on the system, but with a different configuration. For example if the command `check_mysql_health` exists on the system but takes only 4 instead of the expected 6 parameters, because someone modified the check command after the first import.
Should the import throw an error, replace the command argument and may break the monitoring or simply skip this service template? 
Things like this needs to be considered and discussed upfront.

I understand why this would be a very cool feature to have, especially for users who manage multiple openITCOCKPIT servers. With that said, this feature request would bind our resources for quite some time. Therefore I don't think that we will implement this any time soon without funding.
In case you are interested in getting a quote from it-novum, we would be more than happy to develope this feature for you :)

**Comment by nook24** [comment]
Tracked by ITC-2951
